---
- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Install packages via pip
  pip: name={{item}} state=present
  with_items:
    - python-pachyderm

- include: pachyderm.yml
